### ISSUE TITLE
Add validators from assemblies

### ISSUE THREAD

**Issue by nmakhmutov** [enif-lee/grpc-dotnet-validator#7]
In fluentvalidation you can add many validators just from assemblies. It's realy useful when you have a lot of validators in you project. 

For instance:

```C#
var assemblies = AppDomain.CurrentDomain.GetAssemblies();
services.AddValidatorsFromAssemblies(assemblies);
```

And then all you classes inherits from `AbstractValidator<T>` should be added as validator in you project.
Please, could you add this functionality in your project?

**Comment by enif-lee** [comment]
Merged on https://www.nuget.org/packages/GrpcExtensions.AspNetCore.Validation/2.25.6

Thank you.
